### ISSUE TITLE
missing Dataset on datasets

### ISSUE THREAD

**Issue by try-sudo-rm-rf** [vincentarelbundock/Rdatasets#18] opened 2021-11-04 01:29 UTC
on the package datasets is missing this dataset:
 datasets::state.x77

**Comment by vincentarelbundock** [comment] 2021-11-04 01:40
Thanks for the report. The problem is that:

```r
> data(list = "state.x77", package = "datasets")
Warning message:
In data(list = "state.x77", package = "datasets") :
  data set ‘state.x77’ not found
```

**Comment by try-sudo-rm-rf** [comment] 2021-11-04 02:03
![image](https://user-images.githubusercontent.com/92955095/140244985-d2c0d3cd-41e7-447b-9e1d-99cc98694190.png)
here is an image when I load the dataset here is the doc of R dataset: https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/state.html
the state had multiple datasets associate

**Comment by vincentarelbundock** [comment] 2021-11-04 13:52
Right, sorry. This was a cryptic note-to-self.

The problem is that the script I use to scrape datasets calls the `data` function as I showed above. But for some obscure reason, the function does not appear to work in the case of this particular dataset. Fixing this would require modifying this function:

https://github.com/vincentarelbundock/Rdatasets/blob/master/scrape.R#L18

However, I'm not sure how to do it in a general way that will still work with all current datasets and not break anything.

**Comment by vincentarelbundock** [comment] 2022-07-29 15:03
I will close this now because nobody has suggested a solution and I have not found one myself. Everybody should feel free to re-open or keep commenting to suggest a new solution.

**Closed as completed by vincentarelbundock** 2022-07-29 15:03 UTC
